-error CS0144: Cannot create an instance of the abstract class or interface 'Bus': bus is abstract but  need a blank constructor -XmlWriter.Create doesn't seem to be creating document. Will try alternative method for writing to xml -conversion from Element to string when parsing file to load doesn't seem to be working as name is returning blank: works for anything other than converting to string for some reason